# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.mailgun.org:587
mail_admin: donotreply@janduda.slvrcode.com
mail_hostname: janduda.slvrcode.com
mail_user: postmaster@sandbox9e6293dfab19491ab6e47fc0a49a3863.mailgun.org
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml

